import Head from "next/head";
import Image from "next/image";
import { Container } from "@mantine/core";

import Header from "Layouts/Header";

export default function Home() {
  return (
    <Container size="lg" mih="100vh">
      <Head>
        <title>MTSH - Taskify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </Container>
  );
}
